server:
  port: 8081

spring:
  application:
    name: kanban-backend
  profiles:
    active: dev

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info
